### PR TITLE
Added Pricing Controller, tests for Pricing Controller

### PR DESCRIPTION
**Pull request by kaneishere**
Major changes:
-Added Pricing Controller, tests for Pricing Controller

Minor changes:
-corrected typo in account.py
-added black as standard formatter for code base
-added pytest to requirements.txt
-removed build strings from some modules that I can't install on linux

### CODE REVIEW

**Comment by kaneishere** [comment]
PricingController has two methods, get_latest_candles (returns an array of CandleStickResponses) and get_pricing (returns pricing information for the requested instruments). The other relevant api call would be the one that gets a price stream, though I'm not sure yet on how to handle a HTTP stream, so I would look into that when I'm free.

**Comment by nimiew** [comment]
hi, can you update the readme, how to use black as formatter?

**Comment by nimiew** [comment]
Also, please rebase

**Comment by kaneishere** [comment]
Thanks for the reply. I've just updated the README with a short section on setting up black. I've also rebased my code.

**Comment by nimiew** [comment]
@kaneishere, i still see that the branch has conflicts in poandy/controller/instrument.py
I think you are missing thien's commit

**Comment by kaneishere** [comment]
Oops sorry, I just saw thien's commit. I just merged.

**Pull request merged**
